[core]
cache_dir = /workspace/cache
config_dir = /workspace/config
data_dir = /workspace/data
max_tracklist_length = 10000
restore_state = false

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins =
csrf_protection = true
default_app = mopidy

[audio]
mixer = software
mixer_volume =
output = autoaudiosink
buffer_time =

[vkm]
enabled = true
user_agent =
sensitive_cache_path = /workspace/cache/vkm/sensitive.json
cache_path = /workspace/cache/vkm/cache
saved_path = /workspace/cache/vkm/saved

[logging]
verbosity = 4
format = %(levelname)-8s [%(asctime)s] %(name)s\n  %(message)s
color = true
config_file =
